[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn wsgi:application --bind 0.0.0.0:$PORT --log-level debug"
healthcheckPath = "/health/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "covidhelp.settings"
ALLOWED_HOSTS = "*"
PORT = "8000"
DEBUG = "True" 