[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn covidhelp.wsgi:application --timeout 120"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
healthcheckInterval = "30s"

[envs]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "covidhelp.settings"
ALLOWED_HOSTS = "*"
PORT = "8000"
PYTHONUNBUFFERED = "1" 