[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn covidhelp.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"

[envs]
PYTHON_VERSION = "3.12"
DJANGO_SETTINGS_MODULE = "covidhelp.settings"
ALLOWED_HOSTS = "*"
PORT = "8000"
DEBUG = "True" 